### ISSUE TITLE
Design SettingsActivity (SharedPreference)

### ISSUE THREAD

**Issue by woojn90** [woojn90/CoBookE#4]
Setting 화면 구상
UI 및 logic 구현

- [x] 설정할 내용 구상 및 UI 작업 (check, list 등 활용)
- [x] 최초 실행 default tab 설정 추가 (코스 tab, 항목 tab 중 선택)
- [x] SharedPreference 로 default tab 적용

**Comment by dalinaum** [comment]
#8 에서 해결.
